name: Build, Test and Release
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: "oliviertremblaynoel/cpp-builder:latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Release
        run: |
          cmake -S . -B build/release -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build build/release
      - name: Build Debug and Run Tests
        run: |
          cmake -S . -B build/debug -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug
          cmake --build build/debug
          cd build/debug
          ctest --output-on-failure
      
      - name: Set release timestamp
        id: timestamp
        run: echo "value=$(date -u +'%Y-%m-%d-%H-%M')" >> "$GITHUB_OUTPUT"

      - name: Package Release Artifact (if tests passed)
        if: success()
        run: |
          TIMESTAMP=${{ steps.timestamp.outputs.value }}
          mkdir -p release_artifact
          cp ./exec/Release/my_app release_artifact/my_app-$TIMESTAMP
          tar czf release_$TIMESTAMP.tar.gz -C release_artifact .

      - name: Create GitHub Release
        if: success()
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ steps.timestamp.outputs.value }}
          name: "Release ${{ steps.timestamp.outputs.value }}"
          files: release_*.tar.gz
